# Generated by Django 3.2.12 on 2022-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
