# Generated by Django 3.2.12 on 2022-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
