# Generated by Django 3.2.12 on 2022-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(related_name='watched_users', to='movies.Movie'),
        ),
    ]
