# Generated by Django 3.2.12 on 2022-05-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220519_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_actor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_director_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='first_actor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='first_director_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='second_actor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='second_director_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='third_actor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='third_director_id',
            field=models.IntegerField(default=-1),
        ),
    ]
